sudo: required
services:
   - docker
   
before_install:
   - gem install bundler
   - docker build -t rodrr301/docker-react -f Dockerfile.dev .
   
   
script:
# -- --coverage will exit after first test run.
   - docker run rodrr301/docker-react npm run test -- --coverage     